### PR TITLE
Static iPs

### PR DESCRIPTION
**Pull request by noseka1**
Static IPs is currently an experimental feature. If you tried it out, I would be happy to hear your feedback. Please, feel free to leave your comments below.

### CODE REVIEW

**Comment by noseka1** [comment]
Link to the previous conversation related to Static IPs: https://github.com/noseka1/openshift-auto-upi/commit/3c395682f5ec33062b2bb483bb20250c1ef16ffc#comments

**Comment by kristvanbesien** [comment]
WIth what has static IPs already been tested?

I wantesd to try using this with my RHEV cluster.

I tested first on a rhel7 machine. There I got stuck when my machines wouldn't boot. They just displayed a grub prompt. On closer look it was because the `blscfg` command is not found. 

I suspect this is because the core.img installed in the boot iso is too outdated when done via a rhel7 machine.

I then wanted to try doing it from a rhel8 machine, but there I could not find a way to install python-ovirt-engine-sdk4...

**Comment by noseka1** [comment]
@kristvanbesien Thanks for sharing your experience! I tested the static IPs using a helper node running Fedora 31 and also RHEL 8.1. Don't remember testing with RHEL 7 but I would hope that it would work on RHEL 7.8.

Regarding the python-ovirt-engine-sdk4 rpms not available for RHEL 8, I described a workaround here: https://github.com/noseka1/openshift-auto-upi/blob/master/docs/os_specific_config.md#helper-host-os-specific-configuration You can install the ovirt-engine-sdk4 uisng pip:
```
$ pip install ovirt-engine-sdk-python
```

**Comment by noseka1** [comment]
@kristvanbesien You were right. The openshift hosts would not boot when using RHEL7. It is fixed now: https://github.com/noseka1/openshift-auto-upi/issues/5

**Comment by noseka1** [comment]
Static IPs were merge into master and included in the 1.5 release of openshift-auto-upi.

**Pull request closed without merging**
